# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Adventure Game Client

on:
  push:
    paths: 'adventure-game-client/*'
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: shivendra-cyo    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './adventure-game-client/dist/adventure-game-client'      # set this to the path to your web app project
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      working-directory: ./adventure-game-client
      run: |
        npm install
        npm run build -- --prod
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_APPSERVICE_UI }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}